### ISSUE TITLE
Implemenet environment variables for token  and for user/pass

### ISSUE THREAD

**Issue by sea5kg** [sea5kg/git-mirror-repositories#2]
Something like this:
```
repositories:
    example:
        enabled: false
        from: "https://github.com/sea5kg/pipeline-editor-s5"
        to: "http://$env{CREDENTIALS}@another.server.com/sea5kg/pipeline-editor-s5"

```
